# NAME: Stewart Dulaney
# EMAIL: sdulaney@ucla.edu
# ID: 904-064-791 

build:
	gcc lab0.c -o lab0 -g -Wall -Wextra

check:
	echo "TODO: "

clean:
	rm lab0
	rm lab0-904-064-791.tar.gz

dist:
	tar -czf lab0-904-064-791.tar.gz lab0.c Makefile backtrace.png breakpoint.png README
