# NAME: Stewart Dulaney
# EMAIL: sdulaney@ucla.edu
# ID: 904-064-791 

build:
	gcc lab1a.c -o lab1a -g -Wall -Wextra

clean:
	-rm lab1a
	-rm lab1a-904-064-791.tar.gz

dist:
	tar -czf lab1a-904-064-791.tar.gz lab1a.c Makefile README
