# NAME: Stewart Dulaney
# EMAIL: sdulaney@ucla.edu
# ID: 904-064-791 

clean:
	-rm lab4a-904-064-791.tar.gz

dist:
	tar -czf lab4a-904-064-791.tar.gz Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png
